version: '3.5'

services:
  kafka-topics-ui:
    image: ${IMAGE_NAME:-landoop/kafka-topics-ui}:${IMAGE_TAG:-latest}
    environment:
      KAFKA_REST_PROXY_URL: http://kafka-rest:${KR_PORT}
      PROXY:
      MAX_BYTES:
      RECORD_POLL_TIMEOUT:
    networks:
      kafka-net:
      traefik-net:
    healthcheck:
      test: wget --spider -S -t 1 http://localhost:${UI_PORT}
      interval: ${HEALTHCHECK_INTERVAL:-30s}
      timeout: ${HEALTHCHECK_TIMEOUT:-10s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-2m}
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:kafkatopicsui.${PUBLIC_HOSTNAME}
        traefik.backend: kafka-topics-ui
        traefik.port: '${UI_PORT}'
      restart_policy:
        delay: ${RESTART_DELAY:-30s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.5}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-52M}

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    driver: ${KAFKA_NET_DRIVER:-overlay}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    driver: ${TRAEFIK_NET_DRIVER:-overlay}
    external: true
